### ISSUE TITLE
Retrieve All CEF encoded values

### ISSUE THREAD

**Issue by jdp1** [fluenda/ParCEFone#11]
The CEF specification allows user defined extensions.  In order to fully parse a record, all of the fields should be returned.  This should not be limited to the fields that are defined in the specification.

**Comment by trixpan** [comment]
If I recall correctly the custom fields are returned when validation is disabled. 

Do you want to still get the custom fields but with validation enabled?

**Comment by trixpan** [comment]
I see... I was under the impression I had addressed that a while ago but I clearly didn't.

Will work on it

**Comment by jdp1** [comment]
I would want validation for all existing fields (as that is also part of the spec). 

My thoughts were that validation would validate everything, and the user defined (custom) fields would be returned as a string because only the user knows what they contain, which is what I currently have coded.  I could also see validation becoming a type, either strict (only allow defined fields), custom (validate defined fields, return strings for custom) or none (no validation at all).  That becomes a breaking fix though.

 I'm currently running the forked version which addresses #11 and #12, but would like to integrate this back into the main line.

**Comment by jmahonin** [comment]
+1 for this. They don't seem to be explicitly part of the ArcSight CEF spec, but there are additional fields that would be useful to retrieve from the CEF parser, such as:
`categoryDeviceGroup`
`categoryOutcome`
`categorySignificance`
etc.

**Comment by trixpan** [comment]
@jdp1 are you planning to submit a PR?

**Comment by jdp1** [comment]
I do not seem to have permissions to write to a branch:
remote: Permission to fluenda/ParCEFone.git denied to jdp1.

**Comment by jmahonin** [comment]
@jdp1 I think you just need to make a pull request from your local repository / branch, to the fluenda/ParCEFone repo. No need to try push the branch

If you'd prefer, I can make a copy of your branch and submit a PR here.

**Comment by trixpan** [comment]
@jmahonin I cherry-picked his commits into the next brach

Given the significant change in behaviour I made it into a next major version. 

@ottobackwards FYI

**Comment by ottobackwards** [comment]
Hey, thanks for the heads up.  I think that getting this into metron or nifi will be dependent on need

**Comment by jmahonin** [comment]
For what it's worth @ottobackwards, I'm using ParCEFone by way of NiFi's ParseCEF processor. Would it be helpful if I filed a ticket to track this as an improvement in NiFI?

**Comment by ottobackwards** [comment]
Once this is released, I would suggest creating a ticket in NiFi about upgrading the CEF processor to use the new version and capabilities

**Comment by jorgeoa** [comment]
Same request here.
I want to parse and modify CEF events exported from ArcSight in NiFi and some of the fields are not extracted.

**Comment by trixpan** [comment]
fixed by #19
